### ISSUE TITLE
Migrate issues from svn.kvirc.de

### ISSUE THREAD

**Issue by DarthGandalf** [kvirc/KVIrc-old#2]
Numbers 1 and 2 are already taken, so to preserve numbers, need to delete this repo, create new one (just fork), and migrate issues from trac to that new repo.

If you give me access to database on svn.kvirc.de, I can do it myself.

**Comment by wodim** [comment]
Send a mail to Pragma or ping him or something. It would be good to have this up asap

**Comment by wodim** [comment]
@pragmaware who do we need to contact for this? spion?

**Comment by DarthGandalf** [comment]
FTR, https://github.com/trustmaster/trac2github seems to support preserving numbers.

**Comment by pragmaware** [comment]
I'm trying to use trac2github but there are several problems.
Github won't allow too many API connections and the script is unable to import
more than ~50 tickets per run. Then I have to wait several hours to be able
to run it again. Also the tickets aren't associated with the proper users: they appear
all to be reported and owned by me...

See https://github.com/kvirc/kvirc-issue-test , which is my test playground.

**Comment by DarthGandalf** [comment]
I think it's fine to not have them associated with proper users: some users
are not even registered on github, and you can't fill issues on their
behalf anyway.
Mentioning their trac username should be enough.

For some reason https://svn.kvirc.de/kvirc/ticket/79 migrated to
https://github.com/kvirc/kvirc-issue-test/issues/80, though 99 is still 99.

Also, I'll need to cleanup spam comments like
https://github.com/kvirc/kvirc-issue-test/issues/79#issuecomment-114099909
but it'll be easier to do that after migration; trac is too slow :-(

2015-06-22 14:12 GMT+01:00 Szymon Tomasz Stefanek <notifications@github.com>
:

**Comment by DarthGandalf** [comment]
And this is done :)
@ctrlaltca @d00p @J0celyn @namikaze90 I see you have forks of this repo. Please refork from https://github.com/kvirc/KVIrc again.

**Comment by ctrlaltca** [comment]
Well done, and thank you for the reminder :+1:
